export let streamers = [
  // 'https://kick.com/api/v1/channels/drdisrespect',
  'https://kick.com/api/v1/channels/ludwig',
  'https://kick.com/api/v1/channels/xqc',
  'https://kick.com/api/v1/channels/adinross',
  'https://kick.com/api/v1/channels/brucedropemoff',
  'https://kick.com/api/v1/channels/iceposeidon',
  'https://kick.com/api/v1/channels/corinnakopf',
  'https://kick.com/api/v1/channels/eddie',
  'https://kick.com/api/v1/channels/imjoel3004',
  'https://kick.com/api/v1/channels/garydavid',
  'https://kick.com/api/v1/channels/johnnysomali',
  'https://kick.com/api/v1/channels/sam',
  'https://kick.com/api/v1/channels/nickwhite',
  'https://kick.com/api/v1/channels/asianandy',
  'https://kick.com/api/v1/channels/suspendas',
  'https://kick.com/api/v1/channels/burgerplanet',
  'https://kick.com/api/v1/channels/deepak',
  'https://kick.com/api/v1/channels/andymilonakis',
  'https://kick.com/api/v1/channels/hyubsama',
  'https://kick.com/api/v1/channels/officialebz',

];